document.write ('<script language="javascript">\n');
document.write ('<!--\n');
document.write ('var tipo_campanha = "1"; /* 1- publisher 2- advertiser */\n');
document.write ('var mo_swf = "http://athens.mediaops.com.br/microsoft/visualfy08/070912/microsoft_-_treasure_chest_-_superbanner_728x90.swf";\n');
document.write ('var mo_gif = "http://athens.mediaops.com.br/microsoft/visualfy08/070912/microsoft_-_treasure_chest_-_superbanner_728x90.gif";\n');
document.write ('var mo_url = "http://ads1.mediaops.com.br/RealMedia/ads/click_lx.ads/microsoftvisualfy08linhadecodigo/home/1792501834/Top2/microsoft/070726_visualfy08_top2_codigo_ho/super_visualfy08_codigo_home_V2.html/62643436663237363437386362393630";\n');
document.write ('var mo_click = "clickTAG";\n');
document.write ('var mo_largura = "728";\n');
document.write ('var mo_altura = "90";\n');
document.write ('var mo_wmode = "transparent";\n');
document.write ('var Pixel_contador = "";\n');
document.write ('var URL_Teste = "http://www.mediaops.com.br";\n');
document.write ('//-->\n');
document.write ('</script>\n');
document.write ('<script language="javascript" src="http://athens.mediaops.com.br/templates/mediaops_exibe_banner.js">\n');
document.write ('</script>');
